[package]
name = "bson"
version = "0.4.0"
authors = [
    "Y. T. Chung <zonyitoo@gmail.com>",
    "Kevin Yeh <kevinyeah@utexas.edu>"
]
description = "Encoding and decoding support for BSON in Rust"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/zonyitoo/bson-rs"

[lib]
name = "bson"

[dependencies]
byteorder = "1.0"
chrono = "0.2"
libc = "0.2"
rand = "0.3"
rust-crypto = "0.2"
rustc-serialize = "0.3"
serde = "0.9"
time = "0.1"
linked-hash-map = "0.3"
hostname = "^0.1"

[dependencies.decimal]
git = "https://github.com/zonyitoo/decimal"
branch = "patch-1"
